### ISSUE TITLE
Bug in exportFunction when parameter has no type

### ISSUE THREAD

**Issue by erickcomp** [brick/reflection#2]
When parameter has no type, the exportFunction method assigns a nullable sign on the parameter.
Example:

<code>
public function offsetGetForModifying($offset)
</code>

is exported as:

<code>
public function offsetGetForModifying(?$offset)
</code>

To resolve the issue, you should move the verification for nullable parameters, so this verification is placed inside the verification for the parameter type:

Before my proposed modification:
// File: ReflectionTools.php(324)

<pre>
if ($parameter->allowsNull() && ! $parameter->isDefaultValueAvailable()) {
    $result .= '?';
}

if (null !== $type = $parameter->getType()) {
    if (! $type->isBuiltin()) {
        $result .= '\\';
    }

    $result .= $type->getName() . ' ';
}
</pre>
After my proposed modification:
// File: ReflectionTools.php(324)

<pre>
if (null !== $type = $parameter->getType()) {
    if ($parameter->allowsNull() && ! $parameter->isDefaultValueAvailable()) {
        $result .= '?';
    }

    if (! $type->isBuiltin()) {
        $result .= '\\';
    }

    $result .= $type->getName() . ' ';
}
</pre>

I hope I made myself clear with my not-so-good English. But if you have any doubts, we could talk more.
And I thank you for the great tool you made, it saved me hours of development of a function to export a ReflectionFunction signature.

**Comment by BenMorel** [comment]
Hi, could you please provide a test case? i.e. a method signature, expected output, actual output!

**Comment by erickcomp** [comment]
Hi, I got the error with the signature I put in the example above. This one:
Method signature:

<pre>
public function offsetGetForModifying($offset)
</pre>

Is being exported as:

<pre>
public function offsetGetForModifying(?$offset)
</pre>

And the expected output is:

<pre>
public function offsetGetForModifying($offset)
</pre>

**Comment by BenMorel** [comment]
Thank you! Fixed and released as [0.4.1](https://github.com/brick/reflection/releases/tag/0.4.1).

**Comment by erickcomp** [comment]
=D
